print("Escape sequences:")
print("\\" "\\" "\t=> Backslash \\")
print("\\" "'" "\t=> Single quote")
print("\\" '"' "\t=> Double quote")
print("\\" "t" "\t=> Horizontal Tab")
print("\\" "b" "\t=> Backspace")
print("\\" "n" "\t=> Linefid")